### ISSUE TITLE
Erros na função requestBuyTag

### ISSUE THREAD

**Issue by jone22e** [duug-com-br/melhorenvio-sdk-php#3]
Bom dia, achei dois problemas com o código:

Na classe MelhorEnvio.php na função requestBuyTag...

chama: $produto->nome onde na verdade é **$produto->name**

// Adiciona o produto
            $conteudo->products[] = [
                "name" => $produto->nome,
                "quantity" => $produto->quantity,
                "unitary_value" => $produto->insurance_value
            ];

Outro detalhe é que a lista de produtos não é um json, e sim um array. Então não funciona.

// Recupera os produtos
        $produtos = json_decode(json_encode($Products->getProducts()));

**Comment by igorcacerez** [comment]
Obrigado pela ajuda!
